Map<String, String> transferImages = {
  'Metro - Línea 1': 'assets/dashboard/logometro_l1.png',
  'Metro - Línea 2': 'assets/dashboard/logometro_l2.png',
  'Metro - Línea 3': 'assets/dashboard/logometro_l3.png',
  'Metro - Línea 4': 'assets/dashboard/logometro_l4.png',
  'Metro - Línea 5': 'assets/dashboard/logometro_l5.png',
  'Metro - Línea 6': 'assets/dashboard/logometro_l6.png',
  'Metro - Línea 7': 'assets/dashboard/logometro_l7.png',
  'Metro - Línea 8': 'assets/dashboard/logometro_l8.png',
  'Metro - Línea 9': 'assets/dashboard/logometro_l9.png',
  'Metro - Línea A': 'assets/dashboard/logometro_la.png',
  'Metro - Línea B': 'assets/dashboard/logometro_lb.png',
  'Metro - Línea 12': 'assets/dashboard/logometro_l12.png',
  'Metrobús - Línea 1': 'assets/dashboard/logometrobus_l1.png',
  'Metrobús - Línea 2': 'assets/dashboard/logometrobus_l2.png',
  'Metrobús - Línea 3': 'assets/dashboard/logometrobus_l3.png',
  'Metrobús - Línea 4': 'assets/dashboard/logometrobus_l4.png',
  'Metrobús - Línea 5': 'assets/dashboard/logometrobus_l5.png',
  'Metrobús - Línea 6': 'assets/dashboard/logometrobus_l6.png',
  'Metrobús - Línea 7': 'assets/dashboard/logometrobus_l7.png',
  'Tren Ligero': 'assets/dashboard/logotrenligero.png',
  'Trolebús': 'assets/dashboard/logotrenligero.png',
  'Cablebús - Línea 1': 'assets/dashboard/cb_linea_1.png',
  'Cablebús - Línea 2': 'assets/dashboard/cb_linea_2.png',
  'El Insurgente': 'assets/dashboard/logoelinsurgente.png',
  'RTP': 'assets/dashboard/logortp.png',
  'Ecobici': 'assets/dashboard/logoecobici.png',
};
